# Generated by Django 2.2.4 on 2020-04-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoReadsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
